# syntax=docker/dockerfile:1

# Debian GNU/Linux 12 (bookworm)
FROM golang:1.21.5

WORKDIR /app

RUN apt-get update
RUN apt-get install vim tree build-essential git cmake ninja-build avrdude -y

RUN git clone --branch dev --recursive https://github.com/scottfeldman/tinygo.git
WORKDIR /app/tinygo
RUN echo 'deb http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-15 main' | tee /etc/apt/sources.list.d/llvm.list
RUN wget -4 -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
RUN apt-get update
RUN apt-get install clang-15 llvm-15-dev lld-15 libclang-15-dev -y
RUN make llvm-source
RUN make gen-device
RUN go install -tags=llvm15

WORKDIR /app
RUN git clone https://github.com/scottfeldman/drivers.git drivers
WORKDIR /app/drivers
RUN git checkout dev

WORKDIR /app
RUN go work init
RUN go work use tinygo drivers
